steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/truenation-dev/sw-server', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/truenation-dev/sw-server']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'ws-server', '--image', 'gcr.io/truenation-dev/sw-server', '--region', 'europe']
images:
  - gcr.io/truenation-dev/sw-server